# File: customer-service.yml

server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
