global:
  message: Welcome to Order service dev enviroment!!
server:
  port: 8084
message: Hello from Dev!
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: password    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
