global:
  message: Welcome to Order service prod enviroment!!
server:
  port: 8083
message: Hello from prod!
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: password    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
